name: Test
on: pull_request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache test model
        id: cache-model
        uses: actions/cache@v4
        with:
          path: models/
          key: ${{ hashFiles('models/*') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm run download-ci-model
      - run: npm install --ci
      - run: npm run lint
      - run: npm test-ci
